### ISSUE TITLE
Crash 'URL' is not defined'

### ISSUE THREAD

**Issue by Amp3rwater** [m4dhouse/Wireguard-Vpn#10]
```
openATV Enigma2 crash log

crashdate=Sun May  5 18:19:47 2024
compiledate=May 27 2023
skin=MetrixHD/skin.MySkin.xml
sourcedate=2023-05-27
branch=7.2
rev=32256+646b6ae
component=Enigma2

displaymodel=Uno4K SE
imagebuild=20230530
imageversion=7.2
machinebuild=vuuno4kse
model=vuuno4kse

18:19:47.1456 Traceback (most recent call last):
18:19:47.1457   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 260, in action
18:19:47.1462   File "plugin.py", line 450, in plugin.WireguardScreen.CheckUpdate
18:19:47.1466 NameError: name 'URL' is not defined
18:19:47.1466 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xadbaf0b0>>,('wireguard', 'menu')) failed)
```

**Comment by m4dhouse** [comment]
Please install the latest version (python 3.11):
https://github.com/m4dhouse/Wireguard-Vpn/raw/python3/enigma2-plugin-extensions-wireguard-vpn_9.3_all.ipk

**Comment by m4dhouse** [comment]
Please install the latest version:

Python 3.11
https://github.com/m4dhouse/Wireguard-Vpn/raw/python3/enigma2-plugin-extensions-wireguard-vpn_9.4_all.ipk
